### ISSUE TITLE
编译时报错，“Package fontspec Error”，该怎么解决？

### ISSUE THREAD

**Issue by wodaka** [qcts33/BUPTthesis-ctex#12]
![image](https://user-images.githubusercontent.com/7851235/228408253-83253656-eb05-45b7-93a5-40f0d287b04f.png)
编译时很多字体找不到，但是C:\Windows\Fonts里有这些字体，查看文件名字好像对不上。SimSun在字体文件夹里是simsun，ipaexm不知道是什么字体。有同学遇到相同的问题吗，可以讨论一下。

我的系统是win11，使用的软件是texlive + texstudio。

**Comment by qcts33** [comment]
我这两天用类似的配置编译别的文件也出现类似问题，目前不知道是texlive的问题还是Windows的问题……

工作之后几乎抽不出时间来维护这个项目，实在是抱歉

**Comment by wodaka** [comment]
> 我这两天用类似的配置编译别的文件也出现类似问题，目前不知道是texlive的问题还是Windows的问题……
> 
> 工作之后几乎抽不出时间来维护这个项目，实在是抱歉

overleaf是可以正常编译的，回头再研究研究，感谢学长你做的[BUPTthesis-ctex](https://github.com/qcts33/BUPTthesis-ctex)项目，省了不少事:)
