### ISSUE TITLE
自动缩略语

### ISSUE THREAD

**Issue by qcts33** [qcts33/BUPTthesis-ctex#2]
我尝试着基于`glossaries-extra`实现了自动缩略语功能。具体实现可参见`abbreviation`分支。
虽然基本功能有了但缩略语前后的空格却不受ctex的控制。具体输出效果可`abbreviation`分支中`bare_thesis.pdf`的第二章开头。
研究了一下文档实在不知道哪里出问题了，还请有兴趣的小伙伴一起研究一下。

**Comment by qin-nz** [comment]
你说的`glossaries`包似乎跟`biblatex`冲突我没太明白是什么意思，旧的模板好像并没有冲突的情况出现，只是遇到了一个小问题，编译时特别注意一下就好。
https://github.com/rioxwang/BUPTGraduateThesis/issues/20#issuecomment-351324034

**Comment by qcts33** [comment]
@qin-nz  没有冲突吗，那我岂不是白去适配`glossaries-extra`了……
回头有时间处理一下

**Comment by qcts33** [comment]
试了一下，确实不报错，但不知道为啥缩略语表的间距特别大，可是我现在没时间细看文档。暂时不折腾了，目前感觉还是手动管理靠谱。

**Comment by qin-nz** [comment]
@qcts33 加油！看好你哦，等你把这版改的不错了，我就在旧版的README上加上你的链接。

**Comment by qcts33** [comment]
移植了旧模板中的自动缩略语功能，虽然中英文混排的时候自动空格会出问题，但可以用手动空格的方式进行处理。
关闭这个issue，如果有办法解决自动空格的问题，请新开issue。
