### ISSUE TITLE
参考文献列表不显示

### ISSUE THREAD

**Issue by piper-su** [qcts33/BUPTthesis-ctex#6]
同学，我遇到了这样的问题，\cite{item}命令显示的是[item]而不是序号，而且文章末尾不显示文献列表；pub.tex中的\nocite{*}也不显示发表论文列表。

**Comment by qcts33** [comment]
我也是第一次使用biblatex，对这个宏包也不是那么熟悉，但biblatex确实是喜欢出错了还继续编译……
据我的经验应该是bib解析出了什么问题
仔细看一下编译日志，检查bib的内容，检查biber有没有安装，清理临时文件再试试。

**Comment by VivianSnow** [comment]
@piper-su 
应该是你在使用XeLaTex编译后，没有使用Biber编译。如果使用的是TexLive自带的TeXworks。完整的编译顺序是打开bare_thesis.tex
```
xelatex 编译
biber 编译
xelatex 编译
```
参考文献就应该都有了
