### ISSUE TITLE
图例的字体大小的问题

### ISSUE THREAD

**Issue by ryanhuang1014** [qcts33/BUPTthesis-ctex#9]
学长您好，用了你分享的latex模板，感觉挺好的。但是有一些细节的问题，我也自己花了一天时间改了一下，但是有个问题，我没找到办法，还请指教下。

- 研究生院要求的，“若图名采用中英文对照，其英文字体为五号，中文字体为五号楷体。”这点模板里边好像没有支持。

我按照要求，自己进行了修改，在figure的caption里边，手动加上了\kaishu \zihao{5}命令，这样的话，caption里边是对的了。但是有个问题，“图”这个字，好像不会随着变化大小。所以，我看了下，这个字的定义，好像在BUPTthesis.cfg里边，我在里边手动加上大小的限制，但没有效果。想问下，应该在哪里解决这个问题？

**Comment by qcts33** [comment]
我在论坛里回复你了，不知道后来解决了吗？

> 这个功能应该是有实现的，可以在BUPTthesis.cls里找\RequirePackage{caption}那一部分的配置。

**Comment by ryanhuang1014** [comment]
master 分支上是是没有这个问题的
